[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "abc_math"
version = "0.0.1"
description = "Math Package"
authors = [ "Name <email@email.io>", ]
packages = [
  { include = "abc_math" }
]

[tool.poetry.dependencies]
python = ">=3.8"
numpy = "^1.2.3"

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"