name: Deploy Service
on:
  push:
    branches: ['main']

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r projects/names-api/requirements.txt
      - name: Hello World
        run: python projects/names-api/main.py
        shell: sh